### ISSUE TITLE
[1.15.2] Overloaded-Compressed-Blocks throws error with latest Forge versions

### ISSUE THREAD

**Issue by TheUntamed** [CJ-MC-Mods/Overloaded-Compressed-Blocks#10]
https://pastebin.com/yYeC56cr

forge-31.2.23 and above

**Comment by cjm721** [comment]
Please attach the crash-report + latest.log

**Comment by TheUntamed** [comment]
No crash report is created. Just the exception stacktrace I linked.
and this loading screen message if it's any helpful.
![Screenshot_1](https://user-images.githubusercontent.com/48363903/86285721-6c791180-bbe5-11ea-993b-97ec6ecdd111.jpg)

**Comment by cjm721** [comment]
Opps, didn't mean to close it. Need the entire log, not just the snippet

**Comment by TheUntamed** [comment]
The complete log:
https://pastebin.com/TdJ4skpG

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/CJ-MC-Mods/Overloaded-Compressed-Blocks/files/4867937/latest.log)
crashes missing method or class
 Failed to create mod instance. ModID: overloaded_cb, class com.cjm721.overloaded.cb.CompressedBlocks
java.lang.IncompatibleClassChangeError: Found interface net.minecraftforge.forgespi.language.IModInfo$ModVersion, but class was expected
	at com.cjm721.overloaded.cb.CompressedBlocks.lambda$new$0(CompressedBlocks.java:64) ~[?:1.0.12]
