### ISSUE TITLE
Recipes not registering

### ISSUE THREAD

**Issue by angelnc1989** [CJ-MC-Mods/Overloaded-Compressed-Blocks#11]
I tried using your mod on 1.16.1.
The blocks get added to the game with the correct depth, but nothing has recipe even though recipeEnabled is set to true for alle blocks.

**Comment by cjm721** [comment]
This is mentioned in the changelog

https://github.com/CJ-MC-Mods/Overloaded-Compressed-Blocks/blob/1.16/CHANGELOG.md#L4
