### ISSUE TITLE
1.16.3 block adding not working

### ISSUE THREAD

**Issue by SpicyCupcakes** [CJ-MC-Mods/Overloaded-Compressed-Blocks#14]
For some reason, the 1.16.3 version will not allow me to add new blocks.  I did the same thing I did in 1.14.2 to add blocks, but the mod doesn't load them.

**Comment by cjm721** [comment]
Any error or just when you enter the world it does not exist in JEI / craftable?

**Comment by SpicyCupcakes** [comment]
I don't get any error, And the block doesn't exist in jei or crafting.

**Comment by SpicyCupcakes** [comment]
Below is one default entry, the other two are examples.
  {
    "baseRegistryName": "minecraft:.*_concrete$",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "biomesoplenty:fir_log",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "biomesoplenty:fir_planks",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  }

**Comment by SpicyCupcakes** [comment]
hello?

**Comment by braingkk** [comment]
your issue is being looked at as we check all cases [moddedblocks/vanilla, solid/partial, dumb/entity  etc.] as well as recent forge changes that may be causing your specific issue. until we have it fully narrowed down dont expect a reply.

CJ generally commits fixes within 7-30 days, and will post here when a fix exists

**Comment by cjm721** [comment]
Forge changed mod loading again, so my old workaround no longer works. Mods that load before this mod will work fine, but if it ends up loading after it wont.

Still trying to find a way to fix this without having to remove features.

**Comment by cjm721** [comment]
Seem my original hacky idea would work. Was just missing one additional piece so ended up taking many more hours then I expected.

![image](https://user-images.githubusercontent.com/2738614/98438416-da0ae200-209e-11eb-9106-0109695ff720.png)
