### ISSUE TITLE
New bug involving 1.0.17

### ISSUE THREAD

**Issue by SpicyCupcakes** [CJ-MC-Mods/Overloaded-Compressed-Blocks#15]
Now, 1.0.17 cannot run with the same list of mods the previous versions did, it just causes a CTD with a highly vague crash log.

**Comment by cjm721** [comment]
Will need that log / more details.

**Comment by cjm721** [comment]
Also tested on ATM 6 and no issues: 
![image](https://user-images.githubusercontent.com/2738614/98658638-20a74900-22f8-11eb-93d9-d6caa6c45293.png)
