### ISSUE TITLE
Add blocks by wildcard?

### ISSUE THREAD

**Issue by PurpleHel** [CJ-MC-Mods/Overloaded-Compressed-Blocks#16]
Is it possible to add blocks to the config via wildcard? If so, how? If not, consider this a feature request. :D

**Comment by cjm721** [comment]
The default config shows examples how to use regex for matching (path only, don't regex the namespace / modid).

**Comment by PurpleHel** [comment]
Ok, so can't use wildcards for the blocks themselves. got it. Is that something that you might change in the future? Cos it'd be really useful to be able to just add like, anything from a given mod that has 'block' in the name.

**Comment by braingkk** [comment]
the last three examples in the default config show uses of wildcards
``` 
 {
    "baseRegistryName": "minecraft:.*_log",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:.*_wool",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:.*_concrete$",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  }

**Comment by PurpleHel** [comment]
I must have gotten a config from some pack, cos there's no examples in mine. :/ Sorry for the question! I'll make the default config generate and take a look!
