### ISSUE TITLE
Version only loading some Blocks.

### ISSUE THREAD

**Issue by BluMasc** [CJ-MC-Mods/Overloaded-Compressed-Blocks#17]
I use this config:

`[
  {
    "baseRegistryName": "minecraft:gold_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  },
  {
    "baseRegistryName": "minecraft:iron_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  },
  {
    "baseRegistryName": "create:copper_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  },
  {
    "baseRegistryName": "create:zinc_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  },
  {
    "baseRegistryName": "iceandfire:silver_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  },
  {
    "baseRegistryName": "tmechworks:aluminum_ore",
    "depth": 5,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": false
  }
]`

Before i added the aluminum line everything worked fine. Now after i added it, it only loads gold, iron and aluminum. 

I am using version 1.0.16

**Comment by cjm721** [comment]
Update to at least version 19 there where changes in forge that are dealt with in later version
