### ISSUE TITLE
[1.15.1] NoSuchMethodException On AddResourcePack

### ISSUE THREAD

**Issue by ProsperCraft** [CJ-MC-Mods/Overloaded-Compressed-Blocks#6]
Stacktrace-
https://gist.github.com/ProsperCraft/737866a55948c36feafc5e4352a8541a

Full log-
[latest.log](https://github.com/CJ-MC-Mods/Overloaded-Compressed-Blocks/files/4094776/latest.log)

Versions-
Overloaded Compressed Blocks-1.15.1-1.0.8.jar
forge-30-.0.42

**Comment by cjm721** [comment]
Fixed by  79a65054b0559d2455d
