### ISSUE TITLE
Disabled items in config but still show up in JEI

### ISSUE THREAD

**Issue by BedrockLegends** [CJ-MC-Mods/Overloaded-Compressed-Blocks#7]
When you go in the config and change recipe enabled to false it does not remove or hide the items from JEI

**Comment by cjm721** [comment]
In which version

**Comment by BedrockLegends** [comment]
Overloaded Compressed Blocks-1.15.2-1.0.10

**Comment by cjm721** [comment]
Misunderstood your message, thought you were saying recipes weren't being disabled.

Disabling a recipe does not remove an item from showing up in JEI, JEI shows all blocks and items registered whether they have a recipe or not.
