### ISSUE TITLE
server crash on load(forge-1.15.2-31.1.14)

### ISSUE THREAD

**Issue by SDUBZ** [CJ-MC-Mods/Overloaded-Compressed-Blocks#8]
forge-1.15.2-31.1.14
Overloaded Compressed Blocks-1.15.2-1.0.11
logs:
[crash-2020-02-24_11.38.33-server.txt](https://github.com/CJ-MC-Mods/Overloaded-Compressed-Blocks/files/4242799/crash-2020-02-24_11.38.33-server.txt)
latest:
[latest.log](https://github.com/CJ-MC-Mods/Overloaded-Compressed-Blocks/files/4242800/latest.log)

**Comment by cjm721** [comment]
Crash is caused by Inventory Tweaks using LogicalSidedProvider before it is initialized. It is weird that LogicalSidedProvider is not initalized yet (its a forge resource). Will see if I can get around needing to force config loading early (was a bug in 1.14 that prompted it).

**Comment by SDUBZ** [comment]
ok thank you :D

**Comment by cjm721** [comment]
1.0.12 should fix it (119e6bdad493a71e). If not re-open this.
