### ISSUE TITLE
[1.15.2] Blocks not registering?

### ISSUE THREAD

**Issue by lamoyrl90** [CJ-MC-Mods/Overloaded-Compressed-Blocks#9]
I'm trying to add a couple blocks to this, but they don't seem to be registering. They don't show up in JEI and the recipes don't work. Do I need to do something with data packs to enable them?

My config\overloaded_compressed_blocks\compressed.json :

``[
  {
    "baseRegistryName": "minecraft:cobblestone",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:sand",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:stone",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:obsidian",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:netherrack",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:dirt",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:gravel",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:.*_log",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:.*_wool",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "minecraft:.*_concrete$",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "midnight:nightstone",
	"compressedPathRegistryName": "compressed_nightstone",
    "texturePath": "midnight:textures/blocks/nightstone.png",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  },
  {
    "baseRegistryName": "mysticalagriculture:soulstone_cobble",
	"compressedPathRegistryName": "compressed_soulstone_cobble",
    "texturePath": "mysticalagriculture:textures/blocks/soulstone_cobble.png",
    "depth": 16,
    "hardnessMultiplier": 9.0,
    "recipeEnabled": true
  }
]`` .

**Comment by cjm721** [comment]
Need full log from your startup (and including what mods you tested with as working in my test setup). My guess is one of them is failing to register due to name not matching.

Also for 1.15 version the compressedPathRegistryName is no longer needed (doesn't hut anything being there, its just not used).

**Comment by TheUntamed** [comment]
I'm on 1.15.2 as well and just tried to add a vanilla block:

{
    "baseRegistryName": "minecraft:packed_ice",
    "depth": 8,
    "hardnessMultiplier": 1.2,
    "recipeEnabled": true
  },

and it just does nothing. Compressed versions don't show up ingame.

**Comment by cjm721** [comment]
Tested in vanilla 1.15.2 with forge 31.1.14 and 31.1.35. Worked correctly for both.

I am assuming its due to one of the mod items you are adding to be compressed. Without logs / exact mods you are loading with I won't debug further.

Please re-open or create a new issue if you have more details.
